// This file is auto-generated by @hey-api/openapi-ts

export type Body_addNewBooks_add_new_book_post = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthResponse = {
    state?: string;
};

export type Response = {
    message: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ServerHealthHealthGetResponse = HealthResponse;

export type AddNewBooksAddNewBookPostData = {
    category: string;
    description: unknown;
    formData: Body_addNewBooks_add_new_book_post;
    name: string;
};

export type AddNewBooksAddNewBookPostResponse = Response;

export type GetAllBookGetBooksGetData = {
    end: number;
    start: number;
};

export type GetAllBookGetBooksGetResponse = unknown;

export type GetOneBookGetOneBookGetData = {
    id: string;
};

export type GetOneBookGetOneBookGetResponse = unknown;

export type SearchSearchGetData = {
    q: string;
};

export type SearchSearchGetResponse = unknown;

export type ReadOneReadOnePostData = {
    id: string;
};

export type ReadOneReadOnePostResponse = unknown;

export type ReadedBooksReadedBooksGetResponse = unknown;

export type $OpenApiTs = {
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: HealthResponse;
            };
        };
    };
    '/add-new-book': {
        post: {
            req: AddNewBooksAddNewBookPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Response;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/get-books': {
        get: {
            req: GetAllBookGetBooksGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/get-one-book': {
        get: {
            req: GetOneBookGetOneBookGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/search': {
        get: {
            req: SearchSearchGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/read-one': {
        post: {
            req: ReadOneReadOnePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/readed-books': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};